name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
            node-version: lts/*
            cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
